services:
  - type: web
    name: trinity-hrm
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error
      - key: PHP_VERSION
        value: 8.2
    healthCheckPath: /
    autoDeploy: true

