services:
  - type: web
    name: trinity-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: trinity-db
          property: connectionString
      - key: FLASK_ENV
        value: production

